import type { EntityProfile, FieldDefinition } from '../../types'

const fields: FieldDefinition[] = [
  {
    id: 'codigoInterno',
    label: 'Código interno',
    group: 'Identificação',
    kind: 'code',
    requiredForMatch: true,
    aliases: [
      'COD_PRODUTO', 'COD_ITEM', 'CODIGO_PRODUTO', 'CODIGO_ITEM',
      'ID_PRODUTO', 'CODIGO', 'CODPRODUTO',
    ],
  },
  {
    id: 'nome',
    label: 'Descrição',
    group: 'Identificação',
    kind: 'text',
    aliases: [
      'DES_PRODUTO', 'DESCRICAO', 'DES_ITEM', 'NOME_PRODUTO', 'PRODUTO',
      'DESCRICAO_PRODUTO', 'Descrição',
    ],
  },
  {
    id: 'descricaoReduzida',
    label: 'Descrição reduzida',
    group: 'Identificação',
    kind: 'text',
    aliases: ['DES_REDUZIDA', 'DESCRICAO_REDUZIDA', 'DESC_REDUZIDA', 'DES_REDUZ'],
  },
  {
    id: 'codigoBarras',
    label: 'Código de barras',
    group: 'Identificação',
    kind: 'code',
    aliases: [
      'COD_BARRA', 'COD_BARRA_PRINCIPAL', 'CODIGO_BARRAS', 'EAN', 'GTIN', 'EAN13',
      'COD_BARRAS',
    ],
  },
  {
    id: 'unidade',
    label: 'Unidade',
    group: 'Classificação',
    kind: 'text',
    aliases: ['UNIDADE', 'DES_UNIDADE', 'UNIDADE_VENDA', 'DES_UNIDADE_VENDA', 'UND', 'UN'],
  },
  {
    id: 'departamento',
    label: 'Departamento',
    group: 'Classificação',
    kind: 'text',
    aliases: ['DEPARTAMENTO', 'DES_DEPARTAMENTO', 'COD_DEPARTAMENTO'],
  },
  {
    id: 'secao',
    label: 'Seção',
    group: 'Classificação',
    kind: 'text',
    aliases: ['SECAO', 'DES_SECAO', 'SECCAO', 'SEÇÃO'],
  },
  {
    id: 'grupo',
    label: 'Grupo',
    group: 'Classificação',
    kind: 'text',
    aliases: ['GRUPO', 'DES_GRUPO', 'COD_GRUPO', 'GRUPO_PRODUTO'],
  },
  {
    id: 'subgrupo',
    label: 'Subgrupo',
    group: 'Classificação',
    kind: 'text',
    aliases: ['SUBGRUPO', 'DES_SUBGRUPO', 'SUB_GRUPO'],
  },
  {
    id: 'marca',
    label: 'Marca',
    group: 'Classificação',
    kind: 'text',
    aliases: ['MARCA', 'DES_MARCA', 'COD_MARCA'],
  },
  {
    id: 'fornecedor',
    label: 'Fornecedor',
    group: 'Classificação',
    kind: 'text',
    aliases: ['FORNECEDOR', 'COD_FORNECEDOR', 'DES_FORNECEDOR'],
  },
  {
    id: 'precoVenda',
    label: 'Preço venda',
    group: 'Valores',
    kind: 'money',
    aliases: ['PRECO', 'PRECO_VENDA', 'VLR_VENDA', 'VALOR_VENDA', 'VLR_PRECO'],
  },
  {
    id: 'custo',
    label: 'Custo',
    group: 'Valores',
    kind: 'money',
    aliases: ['CUSTO', 'PRECO_CUSTO', 'VLR_CUSTO', 'VALOR_CUSTO'],
  },
  {
    id: 'estoque',
    label: 'Estoque',
    group: 'Valores',
    kind: 'code',
    aliases: ['ESTOQUE', 'QTD_ESTOQUE', 'QUANTIDADE', 'SALDO'],
  },
  {
    id: 'ncm',
    label: 'NCM',
    group: 'Fiscal',
    kind: 'code',
    aliases: ['NCM', 'COD_NCM'],
  },
  {
    id: 'cest',
    label: 'CEST',
    group: 'Fiscal',
    kind: 'code',
    aliases: ['CEST', 'COD_CEST'],
  },
  {
    id: 'cfop',
    label: 'CFOP',
    group: 'Fiscal',
    kind: 'code',
    aliases: ['CFOP', 'COD_CFOP'],
  },
  {
    id: 'cst',
    label: 'CST/CSOSN',
    group: 'Fiscal',
    kind: 'code',
    aliases: ['CST', 'CSOSN', 'CST_CSOSN', 'COD_CST'],
  },
  {
    id: 'origemMercadoria',
    label: 'Origem mercadoria',
    group: 'Fiscal',
    kind: 'code',
    aliases: ['ORIGEM_MERCADORIA', 'ORIGEM', 'COD_ORIGEM'],
  },
  {
    id: 'icms',
    label: 'ICMS',
    group: 'Fiscal',
    kind: 'text',
    aliases: ['ICMS', 'ALIQUOTA_ICMS', 'PERC_ICMS'],
  },
  {
    id: 'pis',
    label: 'PIS',
    group: 'Fiscal',
    kind: 'text',
    aliases: ['PIS', 'ALIQUOTA_PIS', 'PERC_PIS'],
  },
  {
    id: 'cofins',
    label: 'COFINS',
    group: 'Fiscal',
    kind: 'text',
    aliases: ['COFINS', 'ALIQUOTA_COFINS', 'PERC_COFINS'],
  },
  {
    id: 'ativo',
    label: 'Ativo/Inativo',
    group: 'Situação',
    kind: 'boolean',
    aliases: ['ATIVO', 'INATIVO', 'FLG_ATIVO', 'FLG_INATIVO', 'STATUS'],
  },
  {
    id: 'pesoVariavel',
    label: 'Peso variável',
    group: 'Situação',
    kind: 'boolean',
    aliases: ['PESO_VARIAVEL', 'FLG_PESO_VARIAVEL', 'IND_PESO_VARIAVEL'],
  },
  {
    id: 'enviaBalanca',
    label: 'Envia balança',
    group: 'Situação',
    kind: 'boolean',
    aliases: ['ENVIA_BALANCA', 'FLG_BALANCA', 'BALANCA'],
  },
  {
    id: 'observacao',
    label: 'Observação',
    group: 'Observação',
    kind: 'text',
    aliases: ['OBSERVACAO', 'OBS', 'DES_OBSERVACAO', 'Observação'],
  },
]

export const productProfile: EntityProfile = {
  id: 'product',
  label: 'Produtos',
  description: 'Cadastro de itens, preços e classificação mercadológica',
  aliases: ['PRODUTO', 'PRODUTOS', 'ITEM', 'ITENS', 'MERCADORIA'],
  fields,
  statusAliases: ['INATIVO', 'FLG_INATIVO', 'ATIVO', 'FLG_ATIVO', 'STATUS'],
  nameFieldId: 'nome',
  recordLabel: 'Produto',
  showDocumentValidity: false,
  duplicateFieldIds: ['codigoBarras'],
  ambiguousBareTokens: [
    { token: 'STATUS', fieldIds: ['ativo'] },
    { token: 'GRUPO', fieldIds: ['grupo'] },
    { token: 'VALOR', fieldIds: ['precoVenda', 'custo'] },
  ],
}
