import type { EntityProfile, FieldDefinition } from '../../types'

const fields: FieldDefinition[] = [
  {
    id: 'codigoSecao',
    label: 'Código da seção',
    checklistLabel: 'Código seção',
    databaseField: 'COD_SECAO',
    group: 'Subgrupo',
    kind: 'code',
    requiredForMatch: true,
    aliases: ['COD_SECAO'],
    originExactAliases: ['COD_SECAO'],
    targetExactAliases: ['COD_SECAO'],
  },
  {
    id: 'codigoGrupo',
    label: 'Código do grupo',
    checklistLabel: 'Código grupo',
    databaseField: 'COD_GRUPO',
    group: 'Subgrupo',
    kind: 'code',
    requiredForMatch: true,
    aliases: ['COD_GRUPO'],
    originExactAliases: ['COD_GRUPO'],
    targetExactAliases: ['COD_GRUPO'],
  },
  {
    id: 'codigoSubgrupo',
    label: 'Código do subgrupo',
    checklistLabel: 'Código subgrupo',
    databaseField: 'COD_SUB_GRUPO',
    group: 'Subgrupo',
    kind: 'code',
    requiredForMatch: true,
    aliases: ['COD_SUB_GRUPO'],
    originExactAliases: ['COD_SUB_GRUPO'],
    targetExactAliases: ['COD_SUB_GRUPO'],
  },
  {
    id: 'descricaoSubgrupo',
    label: 'Descrição do subgrupo',
    checklistLabel: 'Descrição subgrupo',
    databaseField: 'DES_SUB_GRUPO',
    group: 'Subgrupo',
    kind: 'text',
    aliases: ['DES_SUB_GRUPO'],
    originExactAliases: ['DES_SUB_GRUPO'],
    targetExactAliases: ['DES_SUB_GRUPO'],
  },
]

export const subgroupProfile: EntityProfile = {
  id: 'subgroup',
  label: 'Subgrupos',
  description: 'Homologação do código de seção e grupo vinculados ao código e descrição do subgrupo.',
  aliases: ['SUBGRUPO', 'SUBGRUPOS', 'SUB_GRUPO'],
  fields,
  statusAliases: [],
  nameFieldId: 'descricaoSubgrupo',
  recordLabel: 'Subgrupo',
  duplicateFieldIds: [],
  ambiguousBareTokens: [],
}
