import type { EntityProfile, FieldDefinition } from '../../types'

const fields: FieldDefinition[] = [
  {
    id: 'codigoInterno',
    label: 'Código interno',
    group: 'Identificação',
    kind: 'code',
    requiredForMatch: true,
    aliases: [
      'COD_FORNECEDOR', 'COD_FORNEC', 'COD_FORN', 'FORNECEDOR_CODIGO',
      'CODIGO_FORNECEDOR', 'CODIGO', 'COD_FORNECE', 'ID_FORNECEDOR',
    ],
  },
  {
    id: 'nome',
    label: 'Razão Social',
    group: 'Identificação',
    kind: 'text',
    aliases: [
      'RAZAO_SOCIAL', 'DES_FORNECEDOR', 'NOME_FORNECEDOR', 'FORNECEDOR',
      'NOME', 'DES_RAZAO_SOCIAL', 'NOME_RAZAO_SOCIAL',
    ],
  },
  {
    id: 'apelido',
    label: 'Nome Fantasia',
    group: 'Identificação',
    kind: 'text',
    aliases: ['NOME_FANTASIA', 'FANTASIA', 'DES_FANTASIA', 'APELIDO'],
  },
  {
    id: 'cpfCnpj',
    label: 'CPF/CNPJ',
    group: 'Documentos',
    kind: 'document',
    aliases: [
      'CNPJ', 'CPF', 'CGC', 'NUM_CGC', 'CPF_CNPJ', 'CNPJ_CPF',
      'DOCUMENTO', 'NUM_CNPJ', 'NUM_CPF',
    ],
  },
  {
    id: 'ie',
    label: 'Inscrição Estadual',
    group: 'Documentos',
    kind: 'ie',
    aliases: ['IE', 'INSC_EST', 'NUM_INSC_EST', 'INSCRICAO_ESTADUAL', 'I.E.', 'I.E'],
  },
  {
    id: 'inscricaoMunicipal',
    label: 'Inscrição Municipal',
    group: 'Documentos',
    kind: 'text',
    aliases: ['INSCRICAO_MUNICIPAL', 'INSC_MUN', 'NUM_INSC_MUN', 'IM', 'CCM'],
  },
  {
    id: 'pessoaTipo',
    label: 'Tipo Pessoa',
    group: 'Documentos',
    kind: 'personType',
    aliases: ['TIPO_PESSOA', 'TIP_PESSOA', 'PESSOA', 'FLG_EMPRESA', 'TIPO_FORNECEDOR'],
  },
  {
    id: 'endereco',
    label: 'Endereço',
    group: 'Endereço',
    kind: 'text',
    aliases: ['ENDERECO', 'DES_ENDERECO', 'LOGRADOURO', 'Endereço'],
  },
  {
    id: 'numeroEndereco',
    label: 'Nº Endereço',
    group: 'Endereço',
    kind: 'text',
    aliases: ['NUMERO', 'NUM_ENDERECO', 'NUMERO_ENDERECO', 'NRO_ENDERECO', 'Nº Endereço'],
  },
  {
    id: 'complemento',
    label: 'Complemento',
    group: 'Endereço',
    kind: 'text',
    aliases: ['COMPLEMENTO', 'DES_COMPLEMENTO'],
  },
  {
    id: 'bairro',
    label: 'Bairro',
    group: 'Endereço',
    kind: 'text',
    aliases: ['BAIRRO', 'DES_BAIRRO'],
  },
  {
    id: 'cidade',
    label: 'Cidade',
    group: 'Endereço',
    kind: 'text',
    aliases: ['CIDADE', 'DES_CIDADE', 'MUNICIPIO'],
  },
  {
    id: 'uf',
    label: 'UF',
    group: 'Endereço',
    kind: 'state',
    aliases: ['UF', 'ESTADO', 'SIGLA_UF', 'DES_UF'],
  },
  {
    id: 'cep',
    label: 'CEP',
    group: 'Endereço',
    kind: 'code',
    aliases: ['CEP', 'NUM_CEP', 'COD_CEP'],
  },
  {
    id: 'telefone',
    label: 'Telefone',
    group: 'Contato',
    kind: 'phone',
    aliases: ['TELEFONE', 'FONE', 'NUM_TELEFONE', 'TEL', 'FONE1'],
  },
  {
    id: 'celular',
    label: 'Celular',
    group: 'Contato',
    kind: 'phone',
    aliases: ['CELULAR', 'NUM_CELULAR', 'WHATSAPP'],
  },
  {
    id: 'contato',
    label: 'Contato',
    group: 'Contato',
    kind: 'text',
    aliases: ['CONTATO', 'NOME_CONTATO', 'DES_CONTATO'],
  },
  {
    id: 'email',
    label: 'E-mail',
    group: 'Contato',
    kind: 'text',
    aliases: ['EMAIL', 'E_MAIL', 'DES_EMAIL', 'MAIL'],
  },
  {
    id: 'dataCadastro',
    label: 'Data de Cadastro',
    group: 'Situação',
    kind: 'date',
    aliases: ['DATA_CADASTRO', 'DTA_CADASTRO', 'DT_CADASTRO', 'DATA_INCLUSAO'],
  },
  {
    id: 'statusRegistro',
    label: 'Status',
    group: 'Situação',
    kind: 'text',
    aliases: ['STATUS', 'SITUACAO', 'SIT_FORNECEDOR'],
  },
  {
    id: 'condicaoPagamento',
    label: 'Condição de Pagamento',
    group: 'Financeiro',
    kind: 'text',
    aliases: ['CONDICAO_PAGAMENTO', 'COND_PAGAMENTO', 'CONDICAO', 'Condição'],
  },
  {
    id: 'observacao',
    label: 'Observação',
    group: 'Observação',
    kind: 'text',
    aliases: ['OBSERVACAO', 'OBS', 'DES_OBSERVACAO', 'Observação'],
  },
]

export const supplierProfile: EntityProfile = {
  id: 'supplier',
  label: 'Fornecedores',
  description: 'Cadastro de fornecedores para conversão e homologação',
  aliases: ['FORNECEDOR', 'FORNECEDORES', 'FORNEC', 'FORN', 'SUPPLIER'],
  fields,
  statusAliases: ['INATIVO', 'FLG_INATIVO', 'ATIVO', 'FLG_ATIVO', 'STATUS', 'SITUACAO'],
  nameFieldId: 'nome',
  recordLabel: 'Fornecedor',
  showDocumentValidity: true,
  duplicateFieldIds: ['cpfCnpj', 'ie'],
  ambiguousBareTokens: [
    { token: 'EMPRESA', fieldIds: ['pessoaTipo'] },
    { token: 'STATUS', fieldIds: ['statusRegistro'] },
  ],
}
