import type { EntityProfile, FieldDefinition } from '../../types'

const exactField = (
  id: string,
  label: string,
  checklistLabel: string,
  databaseField: string,
  group: string,
  kind: FieldDefinition['kind'],
  requiredForMatch = false,
): FieldDefinition => ({
  id,
  label,
  checklistLabel,
  databaseField,
  group,
  kind,
  requiredForMatch,
  aliases: [databaseField],
  originExactAliases: [databaseField],
  targetExactAliases: [databaseField],
})

const fields: FieldDefinition[] = [
  exactField(
    'codigoInterno',
    'Código interno',
    'Código Interno',
    'COD_FORNECEDOR',
    'Código Interno',
    'code',
    true,
  ),

  exactField(
    'nome',
    'Razão Social',
    'Razão Social e Fantasia',
    'DES_FORNECEDOR',
    'Razão Social e Fantasia',
    'text',
  ),
  exactField(
    'apelido',
    'Fantasia',
    'Razão Social e Fantasia',
    'DES_FANTASIA',
    'Razão Social e Fantasia',
    'text',
  ),

  exactField(
    'cpfCnpj',
    'CNPJ',
    'CNPJ e IE',
    'NUM_CGC',
    'CNPJ e IE',
    'document',
  ),
  exactField(
    'ie',
    'Inscrição Estadual',
    'CNPJ e IE',
    'NUM_INSC_EST',
    'CNPJ e IE',
    'ie',
  ),

  exactField(
    'endereco',
    'Endereço',
    'Endereço Completo (CEP, Bairro, Cidade, Estado, Etc...)',
    'DES_ENDERECO',
    'Endereço Completo',
    'text',
  ),
  exactField(
    'bairro',
    'Bairro',
    'Endereço Completo (CEP, Bairro, Cidade, Estado, Etc...)',
    'DES_BAIRRO',
    'Endereço Completo',
    'text',
  ),
  exactField(
    'cidade',
    'Cidade',
    'Endereço Completo (CEP, Bairro, Cidade, Estado, Etc...)',
    'DES_CIDADE',
    'Endereço Completo',
    'text',
  ),
  exactField(
    'uf',
    'Estado / UF',
    'Endereço Completo (CEP, Bairro, Cidade, Estado, Etc...)',
    'DES_SIGLA',
    'Endereço Completo',
    'state',
  ),
  exactField(
    'cep',
    'CEP',
    'Endereço Completo (CEP, Bairro, Cidade, Estado, Etc...)',
    'NUM_CEP',
    'Endereço Completo',
    'code',
  ),

  exactField(
    'telefone',
    'Telefone',
    'Telefone / FAX e Contato',
    'NUM_FONE',
    'Telefone / FAX e Contato',
    'phone',
  ),
  exactField(
    'fax',
    'FAX',
    'Telefone / FAX e Contato',
    'NUM_FAX',
    'Telefone / FAX e Contato',
    'phone',
  ),
  exactField(
    'contato',
    'Contato',
    'Telefone / FAX e Contato',
    'DES_CONTATO',
    'Telefone / FAX e Contato',
    'text',
  ),

  exactField(
    'email',
    'E-mail NF-e',
    'E-mail Nfe e E-mail Vendedor',
    'DES_EMAIL',
    'E-mail Nfe e E-mail Vendedor',
    'text',
  ),
  exactField(
    'emailVendedor',
    'E-mail Vendedor',
    'E-mail Nfe e E-mail Vendedor',
    'DES_EMAIL_VEND',
    'E-mail Nfe e E-mail Vendedor',
    'text',
  ),

  exactField(
    'condicaoPagamento',
    'Condição de Pagamento',
    'Condição de Pagamento',
    'NUM_PRAZO',
    'Condição de Pagamento',
    'code',
  ),

  exactField(
    'divisaoFornecedor',
    'Divisão de Fornecedores',
    'Divisão de Fornecedores',
    'COD_CLASSIF',
    'Divisão de Fornecedores',
    'code',
  ),

  exactField(
    'observacao',
    'Observação',
    'Observação',
    'DES_OBSERVACAO',
    'Observação',
    'text',
  ),
]

export const supplierProfile: EntityProfile = {
  id: 'supplier',
  label: 'Fornecedores',
  description: 'Cadastro de fornecedores para conversão e homologação',
  aliases: ['FORNECEDOR', 'FORNECEDORES', 'FORNEC', 'FORN', 'SUPPLIER'],
  fields,
  statusAliases: ['INATIVO', 'FLG_INATIVO', 'ATIVO', 'FLG_ATIVO', 'STATUS', 'SITUACAO'],
  nameFieldId: 'nome',
  recordLabel: 'Fornecedor',
  showDocumentValidity: true,
  duplicateFieldIds: ['cpfCnpj', 'ie'],
  ambiguousBareTokens: [],
}
