import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { productCodeMatchesLength } from '../src/lib/nfce'

assert.equal(productCodeMatchesLength('1', 'under8'), true)
assert.equal(productCodeMatchesLength('1234567', 'under8'), true)
assert.equal(productCodeMatchesLength('12345678', 'under8'), false)
assert.equal(productCodeMatchesLength('123456789', 'over8'), true)
assert.equal(productCodeMatchesLength('12345678', 'over8'), false)
assert.equal(productCodeMatchesLength('ABC123', 'under8'), false)
assert.equal(productCodeMatchesLength('ABC123', 'over8'), false)
assert.equal(productCodeMatchesLength('ABC123', 'all'), true)
assert.equal(productCodeMatchesLength('', 'all'), false)

const page = readFileSync(new URL('../src/pages/NfceAnalyticsPage.tsx', import.meta.url), 'utf8')
const nfceLib = readFileSync(new URL('../src/lib/nfce.ts', import.meta.url), 'utf8')
const sidebar = readFileSync(new URL('../src/components/Sidebar.tsx', import.meta.url), 'utf8')
const app = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')

assert.match(sidebar, /label: 'Pesquisa por produtos'/)
assert.match(app, /NFC-e · Consulta de produtos/)
assert.match(page, /: 'Consulta de produtos'/)

assert.match(nfceLib, /unit: text\(prod, 'uCom'\)/)
assert.match(page, /const salesPackage = String\(item\.unit \?\? ''\)\.trim\(\)/)
assert.match(page, /label="Embalagem de venda" field="salesPackage"/)
assert.match(page, /row\.salesPackage \|\| '—'/)

assert.match(page, /const productLookupOccurrences = useMemo<ProductLookupOccurrence\[]>/)
assert.match(page, /authorizedDocuments\.forEach\(summary =>/)
assert.match(page, /fileName: summary\.fileName/)
assert.match(page, /accessKey: summary\.accessKey/)
assert.match(page, /itemNumber/)
assert.match(page, /issueTimestamp: timestamp\(summary\.issueDate\)/)

assert.match(page, /productSearchKey = normalizeNfceSearch/)
assert.match(page, /nfceSearchKey = normalizeNfceSearch/)
assert.match(page, /normalizedProductCode: normalizeNfceSearch\(productCode\)/)
assert.match(page, /row\.productSearchKey\.includes\(productQuery\)/)
assert.match(page, /row\.nfceSearchKey\.includes\(nfceQuery\)/)

assert.match(page, /productCodeMatchesLength\(row\.productCode, productCodeLength\)/)
assert.match(page, /issueStartFilter/)
assert.match(page, /issueEndFilter/)
assert.match(page, /T00:00:00/)
assert.match(page, /T23:59:59\.999/)
assert.match(page, /row\.issueTimestamp >= issueStart && row\.issueTimestamp <= issueEnd/)
assert.match(page, /aria-label="Data inicial de emissão"/)
assert.match(page, /aria-label="Data final de emissão"/)
assert.match(page, /Período de emissão/)

assert.match(page, /showNfceOccurrences/)
assert.match(page, /Mostrar NFC-e/)
assert.match(page, /Ocultar NFC-e/)
assert.match(page, /if \(showNfceOccurrences\)/)
assert.match(page, /const distinct = new Map<string, ProductLookupRow>\(\)/)
assert.match(page, /if \(!distinctKey \|\| distinct\.has\(distinctKey\)\) return/)
assert.match(page, /ocorrências em NFC-e/)
assert.match(page, /produtos distintos/)

assert.match(page, /SortButton label="NFC-e" field="nfceNumber"/)
assert.match(page, /SortButton label="Emissão" field="issueDate"/)
assert.match(page, /SortButton label="XML de origem" field="fileName"/)
assert.match(page, /SortButton label="Chave de acesso" field="accessKey"/)
assert.match(page, /Nº \{row\.nfceNumber/)
assert.match(page, /Série \{row\.series/)
assert.match(page, /row\.fileName \|\| '—'/)
assert.match(page, /row\.accessKey \|\| '—'/)

assert.match(page, /placeholder="Número, série, chave ou arquivo XML\.\.\."/)
assert.match(page, /<option value="all">Todos<\/option>/)
assert.match(page, /<option value="under8">Menor que 8 dígitos<\/option>/)
assert.match(page, /<option value="over8">Maior que 8 dígitos<\/option>/)

console.log('NFC-e product query, uCom, detailed coupon view, period and optimized indexes: OK')
