import assert from 'node:assert/strict'
import { readFileSync, readdirSync, statSync } from 'node:fs'
import { resolve } from 'node:path'

const sidebar = readFileSync(new URL('../src/components/Sidebar.tsx', import.meta.url), 'utf8')
const app = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')
const main = readFileSync(new URL('../src/main.tsx', import.meta.url), 'utf8')
const updater = readFileSync(new URL('../atualizar-validar-local.cmd', import.meta.url), 'utf8')
const updaterRunner = readFileSync(new URL('./atualizar-validar-local-runner.cmd', import.meta.url), 'utf8')
const validator = readFileSync(new URL('../validar-local.cmd', import.meta.url), 'utf8')
const packageJson = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'))
const viteLauncher = readFileSync(new URL('./iniciar-vite-local.cmd', import.meta.url), 'utf8')

assert.match(sidebar, /\{ id: 'nfce:barcodes', label: 'Pesquisa por produtos' \}/)
assert.doesNotMatch(sidebar, /Códigos < 8 dígitos/)
assert.match(app, /\? 'NFC-e · Consulta de produtos'/)
assert.doesNotMatch(app, /NFC-e · Códigos curtos/)
assert.match(updaterRunner, /Confirmando menu NFC-e "Pesquisa por produtos"/)
assert.match(updaterRunner, /findstr \/C:"label: 'Pesquisa por produtos'"/)
assert.match(validator, /taskkill \/PID %%P \/F/)
assert.equal(packageJson.scripts['serve:local'], 'vite --host localhost --strictPort')
assert.match(main, /localValidation = \['localhost', '127\.0\.0\.1', '::1'\]/)
assert.match(main, /registration\.unregister\(\)/)
assert.match(main, /caches\.delete\(key\)/)
assert.match(updaterRunner, /\[1\/8\] Validando repositorio/)
assert.match(updaterRunner, /\[2\/8\] Posicionando a branch local exatamente/)
assert.match(updaterRunner, /\[3\/8\] Sincronizando exatamente/)
assert.match(updaterRunner, /\[5\/8\] Confirmando SHA local = remoto/)
assert.match(updaterRunner, /\[8\/8\] Iniciando validacao local/)
assert.match(validator, /\[1\/6\] Preparando ambiente local isolado por versao/)
assert.match(validator, /\[3\/6\] Limpando build/)
assert.match(validator, /\[6\/6\] Confirmando fonte servida e executando smoke test no Edge/)
assert.match(updaterRunner, /git reset --hard origin\/homologacao-local-validacao/)
assert.match(updaterRunner, /marcoantunes171989\/PrimeCheck/)
assert.match(updaterRunner, /\[7\/8\] Confirmando tela Consulta de produtos/)
assert.match(validator, /NAO USE http:\/\/localhost:4173/)
assert.match(validator, /verify-local-served-build\.mjs/)
assert.match(validator, /LOCAL_PORT/)
assert.match(validator, /VITE_LAUNCHER/)
assert.match(validator, /iniciar-vite-local\.cmd/)
assert.match(validator, /PORT_READY/)
assert.match(validator, /LISTENING/)
assert.match(validator, /VITE_LOG/)
assert.match(viteLauncher, /call npm run serve:local -- --port %LOCAL_PORT%/)
assert.match(validator, /4200 \+ \(\[Convert\]::ToInt32/)
assert.match(validator, /Pesquisa por produtos/)
assert.match(validator, /Consulta de produtos/)
assert.match(validator, /Microsoft.*Edge.*msedge\.exe/)
assert.match(validator, /--headless=new/)
assert.match(validator, /--dump-dom/)
assert.match(main, /PrimeCheckRuntimeBoundary/)
assert.match(main, /data-primecheck-runtime-error/)
assert.match(updater, /RUNNER_TEMP/)
assert.match(updater, /copy \/Y "%RUNNER_SOURCE%" "%RUNNER_TEMP%"/)
assert.match(updater, /call "%RUNNER_TEMP%" "%PROJECT_DIR%"/)
assert.doesNotMatch(updater, /git fetch|git reset|git switch|git checkout/)
assert.match(updaterRunner, /git checkout -B homologacao-local-validacao origin\/homologacao-local-validacao/)
assert.doesNotMatch(updaterRunner, /git switch -c/)
assert.doesNotMatch(updaterRunner, /git show-ref --verify/)

console.log('NFC-e menu label and local preview freshness verification: OK')


const readDistText = (dir: string): string =>
  readdirSync(dir)
    .map(name => resolve(dir, name))
    .map(path => statSync(path).isDirectory() ? readDistText(path) : (/\.(?:js|html|css)$/.test(path) ? readFileSync(path, 'utf8') : ''))
    .join('\n')

const distText = readDistText(resolve('dist'))
assert.match(distText, /Pesquisa por produtos/)
assert.match(distText, /NFC-e · Consulta de produtos/)
assert.doesNotMatch(distText, /Códigos < 8 dígitos/)
assert.doesNotMatch(distText, /NFC-e · Códigos curtos/)

console.log('Built bundle contains the updated NFC-e menu label: OK')
