import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { productCodeMatchesLength } from '../src/lib/nfce'

assert.equal(productCodeMatchesLength('1', 'under8'), true)
assert.equal(productCodeMatchesLength('1234567', 'under8'), true)
assert.equal(productCodeMatchesLength('12345678', 'under8'), false)
assert.equal(productCodeMatchesLength('123456789', 'over8'), true)
assert.equal(productCodeMatchesLength('12345678', 'over8'), false)
assert.equal(productCodeMatchesLength('ABC123', 'under8'), false)
assert.equal(productCodeMatchesLength('ABC123', 'over8'), false)
assert.equal(productCodeMatchesLength('ABC123', 'all'), true)
assert.equal(productCodeMatchesLength('', 'all'), false)

const page = readFileSync(new URL('../src/pages/NfceAnalyticsPage.tsx', import.meta.url), 'utf8')
const sidebar = readFileSync(new URL('../src/components/Sidebar.tsx', import.meta.url), 'utf8')
const app = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')

assert.match(sidebar, /label: 'Pesquisa por produtos'/)
assert.match(app, /NFC-e · Consulta de produtos/)
assert.match(page, /: 'Consulta de produtos'/)
assert.match(page, /const productLookupOccurrences = useMemo<ProductLookupOccurrence\[]>/)
assert.match(page, /authorizedDocuments\.forEach\(summary =>/)
assert.match(page, /productCodeMatchesLength\(row\.productCode, productCodeLength\)/)
assert.match(page, /searchIncludes\(productQuery, \[row\.productCode, row\.description\]\)/)
assert.match(page, /row\.nfceNumber/)
assert.match(page, /row\.series/)
assert.match(page, /dayKey\(row\.issueDate\) === issueDateFilter/)
assert.match(page, /type ProductLookupRow = \{[\s\S]*?productCode: string[\s\S]*?description: string[\s\S]*?\}/)
assert.doesNotMatch(page, /type ProductLookupRow = ProductLookupOccurrence/)
assert.match(page, /const distinct = new Map<string, ProductLookupRow>\(\)/)
assert.match(page, /distinct\.has\(distinctKey\)/)
assert.match(page, /<option value="all">Todos<\/option>/)
assert.match(page, /<option value="under8">Menor que 8 dígitos<\/option>/)
assert.match(page, /<option value="over8">Maior que 8 dígitos<\/option>/)
assert.match(page, /placeholder="Número ou série da NFC-e\.\.\."/)
assert.match(page, /aria-label="Filtrar por data de emissão"/)
assert.match(page, /nfce-product-lookup-table/)
assert.doesNotMatch(page, /Arquivo XML de origem/)
assert.match(page, /SortButton label="Código do produto \(<cProd>\)"/)
assert.match(page, /SortButton label="Descrição"/)

console.log('NFC-e product lookup filters and DISTINCT verification: OK')
