SELECT 
TAB_SECAO.COD_SECAO,
TAB_SECAO.DES_SECAO,
TAB_GRUPO.COD_GRUPO,
TAB_GRUPO.DES_GRUPO,
--TAB_CENTRO_CUSTO.NUM_CENTRO_CUSTO,
--TAB_PLANO_CONTA.CONTA_REDUZIDA AS CONTA_REDUZIDA_CTB, 
TAB_SUBGRUPO.COD_SUB_GRUPO,
TAB_SUBGRUPO.DES_SUB_GRUPO 
FROM 
TAB_SECAO, 
TAB_GRUPO, 
TAB_SUBGRUPO   
LEFT JOIN TAB_CENTRO_CUSTO ON 
  TAB_SUBGRUPO.COD_CENTRO_CUSTO = TAB_CENTRO_CUSTO.COD_CENTRO_CUSTO 
LEFT JOIN TAB_PLANO_CONTA ON 
  TAB_SUBGRUPO.COD_CONTA_CTB_RESULT = TAB_PLANO_CONTA.COD_CONTA 
WHERE 
TAB_SECAO.COD_SECAO = TAB_GRUPO.COD_SECAO 
AND 
TAB_SECAO.COD_SECAO = TAB_SUBGRUPO.COD_SECAO 
AND 
TAB_GRUPO.COD_GRUPO = TAB_SUBGRUPO.COD_GRUPO 
ORDER BY TAB_SECAO.COD_SECAO, TAB_GRUPO.COD_GRUPO, TAB_SUBGRUPO.COD_SUB_GRUPO;
